2019-09-19 15:03:05,077 INFO: Microblog startup [in /Users/minlixu/Desktop/ILC/training-ground/flask/c8_follower/app/__init__.py:46]
2019-09-19 15:05:32,651 INFO: Microblog startup [in /Users/minlixu/Desktop/ILC/training-ground/flask/c8_follower/app/__init__.py:46]
2019-09-19 15:29:26,771 INFO: Microblog startup [in /Users/minlixu/Desktop/ILC/training-ground/flask/c8_follower/app/__init__.py:46]
2019-09-19 15:42:59,848 INFO: Microblog startup [in /Users/minlixu/Desktop/ILC/training-ground/flask/c8_follower/app/__init__.py:46]
2019-09-25 16:31:44,686 INFO: Microblog startup [in /Users/minlixu/Desktop/ILC/training-ground/flask/c9_pagination/app/__init__.py:46]
2019-09-25 16:31:58,325 ERROR: Exception on /index [GET] [in /anaconda3/envs/web/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/minlixu/Desktop/ILC/training-ground/flask/c9_pagination/app/routes.py", line 39, in index
    form=form, posts=posts)
NameError: name 'posts' is not defined
2019-09-25 16:32:25,069 INFO: Microblog startup [in /Users/minlixu/Desktop/ILC/training-ground/flask/c9_pagination/app/__init__.py:46]
2019-09-25 16:32:32,470 ERROR: Exception on /explore [GET] [in /anaconda3/envs/web/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/minlixu/Desktop/ILC/training-ground/flask/c9_pagination/app/routes.py", line 150, in explore
    form=form, posts=posts)
NameError: name 'form' is not defined
2019-09-25 16:32:33,616 ERROR: Exception on /explore [GET] [in /anaconda3/envs/web/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/minlixu/Desktop/ILC/training-ground/flask/c9_pagination/app/routes.py", line 150, in explore
    form=form, posts=posts)
NameError: name 'form' is not defined
2019-09-25 16:32:33,937 ERROR: Exception on /explore [GET] [in /anaconda3/envs/web/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/minlixu/Desktop/ILC/training-ground/flask/c9_pagination/app/routes.py", line 150, in explore
    form=form, posts=posts)
NameError: name 'form' is not defined
2019-09-25 16:32:34,125 ERROR: Exception on /explore [GET] [in /anaconda3/envs/web/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/minlixu/Desktop/ILC/training-ground/flask/c9_pagination/app/routes.py", line 150, in explore
    form=form, posts=posts)
NameError: name 'form' is not defined
2019-09-25 16:32:34,305 ERROR: Exception on /explore [GET] [in /anaconda3/envs/web/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/anaconda3/envs/web/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/minlixu/Desktop/ILC/training-ground/flask/c9_pagination/app/routes.py", line 150, in explore
    form=form, posts=posts)
NameError: name 'form' is not defined
2019-09-25 16:33:08,226 INFO: Microblog startup [in /Users/minlixu/Desktop/ILC/training-ground/flask/c9_pagination/app/__init__.py:46]
2019-09-25 16:35:37,609 INFO: Microblog startup [in /Users/minlixu/Desktop/ILC/training-ground/flask/c9_pagination/app/__init__.py:46]
2019-09-25 16:36:44,201 INFO: Microblog startup [in /Users/minlixu/Desktop/ILC/training-ground/flask/c9_pagination/app/__init__.py:46]
2019-09-25 16:41:40,442 INFO: Microblog startup [in /Users/minlixu/Desktop/ILC/training-ground/flask/c9_pagination/app/__init__.py:46]
